tests/riscv32: Update generated files
Signed-off-by: Anton Johansson <anjo@rev.ng>

diff --git a/tests/tcg/riscv32/Makefile.target b/tests/tcg/riscv32/Makefile.target
--- a/tests/tcg/riscv32/Makefile.target
+++ b/tests/tcg/riscv32/Makefile.target
@@ -97,38 +97,133 @@ run-smrnmi-asm-tests: $(SMRNMI_OUT_ASM_DIR)/*
 
 .PHONY: build-xqci-c-tests-dir
 build-xqci-c-tests-dir:
-	mkdir -p $(OUT_C_DIR)
-	mkdir -p $(OUT_C_CODE_DIR)
-	mkdir -p $(OUT_C_OBJECT_DIR)
-	mkdir -p $(OUT_C_BIN_DIR)
+	mkdir -p $(XQCI_OUT_C_DIR)
+	mkdir -p $(XQCI_OUT_C_CODE_DIR)
+	mkdir -p $(XQCI_OUT_C_OBJECT_DIR)
+	mkdir -p $(XQCI_OUT_C_BIN_DIR)
+
+.PHONY: build-xqccmp-c-tests-dir
+build-xqccmp-c-tests-dir:
+	mkdir -p $(XQCCMP_OUT_C_DIR)
+	mkdir -p $(XQCCMP_OUT_C_CODE_DIR)
+	mkdir -p $(XQCCMP_OUT_C_OBJECT_DIR)
+	mkdir -p $(XQCCMP_OUT_C_BIN_DIR)
+
+.PHONY: build-smrnmi-c-tests-dir
+build-smrnmi-c-tests-dir:
+	mkdir -p $(SMRNMI_OUT_C_DIR)
+	mkdir -p $(SMRNMI_OUT_C_CODE_DIR)
+	mkdir -p $(SMRNMI_OUT_C_OBJECT_DIR)
+	mkdir -p $(SMRNMI_OUT_C_BIN_DIR)
 
 .PHONY: build-xqci-c-tests-code
 build-xqci-c-tests-code: build-xqci-c-tests-dir
-	@for in_io in $(KLEE_IO_DIR)/*; do \
+	@for in_io in $(XQCI_KLEE_IO_DIR)/*; do \
 		instname=$$(basename $$in_io); \
 		echo "Generating C code for" $$instname; \
-		python $(SRC)/c.py --inst-dir $(INST_DIR) --inst-name $$instname --io-file $$in_io --out $(OUT_C_CODE_DIR)/$$instname.c; \
+		python $(SRC)/c.py --inst-dir $(XQCI_INST_DIR) --inst-name $$instname --io-file $$in_io --out $(XQCI_OUT_C_CODE_DIR)/$$instname.c; \
 	done
 
 .PHONY: build-xqci-c-tests-obj
 build-xqci-c-tests-obj: build-xqci-c-tests-code
-	@for file in $(OUT_C_CODE_DIR)/*; do \
+	@for file in $(XQCI_OUT_C_CODE_DIR)/*; do \
 		instname=$$(basename $$file); \
 		echo "Building obj for" $$instname; \
-		$(CC) -c --target=riscv32-unknown-linux-gnu -menable-experimental-extensions -march=rvi20u32_xqci -o $(OUT_C_OBJECT_DIR)/$$instname.o $$file; \
+		$(CC) -c --target=riscv32-unknown-linux-gnu -menable-experimental-extensions -march=rvi20u32_xqci -o $(XQCI_OUT_C_OBJECT_DIR)/$$instname.o $$file; \
 	done
 
 .PHONY: build-xqci-c-tests
 build-xqci-c-tests: build-xqci-c-tests-obj
-	@for file in $(OUT_C_OBJECT_DIR)/*; do \
+	@for file in $(XQCI_OUT_C_OBJECT_DIR)/*; do \
 		instname=$$(basename $$file); \
 		echo "Linking obj for" $$instname; \
-		$(LD) -T $(SRC)/mem-test-page.ld -o $(OUT_C_BIN_DIR)/$$instname $$file; \
+		$(LD) -T $(SRC)/mem-test-page.ld -o $(XQCI_OUT_C_BIN_DIR)/$$instname $$file; \
 	done
 
 .PHONY: run-xqci-c-tests
-run-xqci-c-tests: $(OUT_C_BIN_DIR)/*
-	@for exe in $(OUT_C_BIN_DIR)/*; do \
+run-xqci-c-tests: $(XQCI_OUT_C_BIN_DIR)/*
+	@for exe in $(XQCI_OUT_C_BIN_DIR)/*; do \
+		out=$$($(QEMU) -cpu rv32,zcmp=true,zcd=false,d=false,zcb=true,zilsd=true,zclsd=true,zcd=false,d=false,c=false $$exe); \
+		err=$$?; \
+		if [ $$err -eq 0 ]; then \
+			echo "PASS" $$exe; \
+		else \
+			echo "FAIL ($${err}) $${exe}"; \
+		fi; \
+	done
+
+
+
+
+
+
+.PHONY: build-xqccmp-c-tests-code
+build-xqccmp-c-tests-code: build-xqccmp-c-tests-dir
+	@for in_io in $(XQCCMP_KLEE_IO_DIR)/*; do \
+		instname=$$(basename $$in_io); \
+		echo "Generating C code for" $$instname; \
+		python $(SRC)/c.py --inst-dir $(XQCCMP_INST_DIR) --inst-name $$instname --io-file $$in_io --out $(XQCCMP_OUT_C_CODE_DIR)/$$instname.c; \
+	done
+
+.PHONY: build-xqccmp-c-tests-obj
+build-xqccmp-c-tests-obj: build-xqccmp-c-tests-code
+	@for file in $(XQCCMP_OUT_C_CODE_DIR)/*; do \
+		instname=$$(basename $$file); \
+		echo "Building obj for" $$instname; \
+		$(CC) -c --target=riscv32-unknown-linux-gnu -menable-experimental-extensions -march=rvi20u32_xqccmp0p1 -o $(XQCCMP_OUT_C_OBJECT_DIR)/$$instname.o $$file; \
+	done
+
+.PHONY: build-xqccmp-c-tests
+build-xqccmp-c-tests: build-xqccmp-c-tests-obj
+	@for file in $(XQCCMP_OUT_C_OBJECT_DIR)/*; do \
+		instname=$$(basename $$file); \
+		echo "Linking obj for" $$instname; \
+		$(LD) -T $(SRC)/mem-test-page.ld -o $(XQCCMP_OUT_C_BIN_DIR)/$$instname $$file; \
+	done
+
+.PHONY: run-xqccmp-c-tests
+run-xqccmp-c-tests: $(XQCCMP_OUT_C_BIN_DIR)/*
+	@for exe in $(XQCCMP_OUT_C_BIN_DIR)/*; do \
+		out=$$($(QEMU) -cpu rv32,zcmp=true,zcd=false,d=false,zcb=true,zilsd=true,zclsd=true,zcd=false,d=false,c=false $$exe); \
+		err=$$?; \
+		if [ $$err -eq 0 ]; then \
+			echo "PASS" $$exe; \
+		else \
+			echo "FAIL ($${err}) $${exe}"; \
+		fi; \
+	done
+
+
+
+
+
+.PHONY: build-smrnmi-c-tests-code
+build-smrnmi-c-tests-code: build-smrnmi-c-tests-dir
+	@for in_io in $(SMRNMI_KLEE_IO_DIR)/*; do \
+		instname=$$(basename $$in_io); \
+		echo "Generating C code for" $$instname; \
+		python $(SRC)/c.py --inst-dir $(SMRNMI_INST_DIR) --inst-name $$instname --io-file $$in_io --out $(SMRNMI_OUT_C_CODE_DIR)/$$instname.c; \
+	done
+
+.PHONY: build-smrnmi-c-tests-obj
+build-smrnmi-c-tests-obj: build-smrnmi-c-tests-code
+	@for file in $(SMRNMI_OUT_C_CODE_DIR)/*; do \
+		instname=$$(basename $$file); \
+		echo "Building obj for" $$instname; \
+		$(CC) -c --target=riscv32-unknown-linux-gnu -menable-experimental-extensions -march=rvi20u32_smrnmi -o $(SMRNMI_OUT_C_OBJECT_DIR)/$$instname.o $$file; \
+	done
+
+.PHONY: build-smrnmi-c-tests
+build-smrnmi-c-tests: build-smrnmi-c-tests-obj
+	@for file in $(SMRNMI_OUT_C_OBJECT_DIR)/*; do \
+		instname=$$(basename $$file); \
+		echo "Linking obj for" $$instname; \
+		$(LD) -T $(SRC)/mem-test-page.ld -o $(SMRNMI_OUT_C_BIN_DIR)/$$instname $$file; \
+	done
+
+.PHONY: run-smrnmi-c-tests
+run-smrnmi-c-tests: $(SMRNMI_OUT_C_BIN_DIR)/*
+	@for exe in $(SMRNMI_OUT_C_BIN_DIR)/*; do \
 		out=$$($(QEMU) -cpu rv32,zcmp=true,zcd=false,d=false,zcb=true,zilsd=true,zclsd=true,zcd=false,d=false,c=false $$exe); \
 		err=$$?; \
 		if [ $$err -eq 0 ]; then \
